wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687983697.715406
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.15.4
      8:
      - 5
